FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["salao-app.Application/salao-app.Application.csproj", "salao-app.Application/"]
RUN dotnet restore "salao-app.Application/salao-app.Application.csproj"
COPY . .
WORKDIR "/src/salao-app.Application"
RUN dotnet build "salao-app.Application.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "salao-app.Application.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "salao-app.Application.dll"]
